name: fs
description: A dart:io's FileSystem available for web.
version: 1.0.0
homepage: https://fs.vise.sbs/
repository: https://github.com/vise-maps/fs/

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
