name: fs
description: A dart:io's FileSystem available for web.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: {path_provider: ^2.0.11}
