name: Dart

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3
      - name: Install dependencies
        run: dart pub get
      - name: Generate docs
        run: dart doc . --auto-include-dependencies --output docs
      - name: Using custom domains
        run: echo "fs.vise.sbs" >> docs/CNAME